// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const LinkClickHandler: typeof import('D:/Dashlit/apps/extension/utils/helpers')['LinkClickHandler']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const browser: typeof import('wxt/browser')['browser']
  const cn: typeof import('D:/Dashlit/apps/extension/utils/tailwind')['cn']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const settingsBackgroundData: typeof import('D:/Dashlit/apps/extension/utils/commonData')['settingsBackgroundData']
  const settingsTabHeaders: typeof import('D:/Dashlit/apps/extension/utils/commonData')['settingsTabHeaders']
  const storage: typeof import('wxt/storage')['storage']
}
