export const USER_SETTINGS_REQUEST = "USER_SETTINGS_REQUEST";
export const USER_SETTINGS_SUCCESS = "USER_SETTINGS_SUCCESS";
export const USER_SETTINGS_FAIL = "USER_SETTINGS_FAIL";

export const USER_MY_QUOTES_REQUEST = "USER_MY_QUOTES_REQUEST";
export const USER_MY_QUOTES_SUCCESS = "USER_MY_QUOTES_SUCCESS";
export const USER_MY_QUOTES_FAIL = "USER_MY_QUOTES_FAIL";
